#!/bin/sh

# from WordSplitting page at BashGuide.
# http://mywiki.wooledge.org/WordSplitting
# shows number of arguments passed
# usage = $ args some "thing else"
# output = 2 args: <some> <thing else>

printf "%d args:" $#
printf " <%s>" "$@"
printf "\n"
