#!/bin/bash

# I just quickly made this while playing with Packages and Rich Trouton's
# post here http://derflounder.wordpress.com/2013/11/03/re-packaging-installer-packages-with-packages/
# to get office cleanly back off my machine. This is why it does not search out
# or account for other versions of the installers/updaters to build the array

pkg_remove=(
com.microsoft.lync.all.lync.pkg.14.0.2
com.microsoft.lync.all.meetingjoinplugin.pkg.14.0.2
com.microsoft.mau.all.autoupdate.pkg.2.3.6
com.microsoft.merp.all.errorreporting.pkg.2.2.9
com.microsoft.office.all.automator.pkg.14.3.0
com.microsoft.office.all.automator.pkg.14.3.9.update
com.microsoft.office.all.clipart_search9.pkg.14.3.0
com.microsoft.office.all.core.pkg.14.3.0
com.microsoft.office.all.core.pkg.14.3.9.update
com.microsoft.office.all.dcc.pkg.14.3.0
com.microsoft.office.all.dcc.pkg.14.3.9.update
com.microsoft.office.all.dock.pkg.14.3.0
com.microsoft.office.all.equationeditor.pkg.14.3.0
com.microsoft.office.all.equationeditor.pkg.14.3.9.update
com.microsoft.office.all.excel.pkg.14.3.0
com.microsoft.office.all.excel.pkg.14.3.9.update
com.microsoft.office.all.fix_permissions.pkg.14.3.9
com.microsoft.office.all.fonts.pkg.14.3.0
com.microsoft.office.all.fonts.pkg.14.3.9.update
com.microsoft.office.all.graph.pkg.14.3.0
com.microsoft.office.all.graph.pkg.14.3.9.update
com.microsoft.office.all.launch.pkg.14.3.0
com.microsoft.office.all.licensing.pkg.14.3.0
com.microsoft.office.all.ooxml.pkg.14.3.0
com.microsoft.office.all.ooxml.pkg.14.3.9.update
com.microsoft.office.all.outlook.pkg.14.3.0
com.microsoft.office.all.outlook.pkg.14.3.9.update
com.microsoft.office.all.powerpoint.pkg.14.3.0
com.microsoft.office.all.powerpoint.pkg.14.3.9.update
com.microsoft.office.all.proofing_brazilian.pkg.14.3.0
com.microsoft.office.all.proofing_brazilian.pkg.14.3.9.update
com.microsoft.office.all.proofing_catalan.pkg.14.3.0
com.microsoft.office.all.proofing_catalan.pkg.14.3.9.update
com.microsoft.office.all.proofing_czech.pkg.14.3.0
com.microsoft.office.all.proofing_czech.pkg.14.3.9.update
com.microsoft.office.all.proofing_danish.pkg.14.3.0
com.microsoft.office.all.proofing_danish.pkg.14.3.9.update
com.microsoft.office.all.proofing_dutch.pkg.14.3.0
com.microsoft.office.all.proofing_dutch.pkg.14.3.9.update
com.microsoft.office.all.proofing_english.pkg.14.3.0
com.microsoft.office.all.proofing_english.pkg.14.3.9.update
com.microsoft.office.all.proofing_finnish.pkg.14.3.0
com.microsoft.office.all.proofing_finnish.pkg.14.3.9.update
com.microsoft.office.all.proofing_french.pkg.14.3.0
com.microsoft.office.all.proofing_french.pkg.14.3.9.update
com.microsoft.office.all.proofing_german.pkg.14.3.0
com.microsoft.office.all.proofing_german.pkg.14.3.9.update
com.microsoft.office.all.proofing_italian.pkg.14.3.0
com.microsoft.office.all.proofing_italian.pkg.14.3.9.update
com.microsoft.office.all.proofing_italian_grammar.pkg.14.3.9.update
com.microsoft.office.all.proofing_japanese.pkg.14.3.0
com.microsoft.office.all.proofing_japanese.pkg.14.3.9.update
com.microsoft.office.all.proofing_norwegian.pkg.14.3.0
com.microsoft.office.all.proofing_norwegian.pkg.14.3.9.update
com.microsoft.office.all.proofing_polish.pkg.14.3.0
com.microsoft.office.all.proofing_polish.pkg.14.3.9.update
com.microsoft.office.all.proofing_portuguese.pkg.14.3.0
com.microsoft.office.all.proofing_portuguese.pkg.14.3.9.update
com.microsoft.office.all.proofing_russian.pkg.14.3.0
com.microsoft.office.all.proofing_russian.pkg.14.3.9.update
com.microsoft.office.all.proofing_spanish.pkg.14.3.0
com.microsoft.office.all.proofing_spanish.pkg.14.3.9.update
com.microsoft.office.all.proofing_swedish.pkg.14.3.0
com.microsoft.office.all.proofing_swedish.pkg.14.3.9.update
com.microsoft.office.all.proofing_turkish.pkg.14.3.0
com.microsoft.office.all.proofing_turkish.pkg.14.3.9.update
com.microsoft.office.all.quit.pkg.14.3.0
com.microsoft.office.all.quit.pkg.14.3.9.update
com.microsoft.office.all.required_office.pkg.14.3.0
com.microsoft.office.all.setupasst.pkg.14.3.0
com.microsoft.office.all.sharepointbrowserplugin.pkg.14.3.0
com.microsoft.office.all.sharepointbrowserplugin.pkg.14.3.9.update
com.microsoft.office.all.slt_std.pkg.14.3.0
com.microsoft.office.all.vb.pkg.14.3.0
com.microsoft.office.all.vb.pkg.14.3.9.update
com.microsoft.office.all.word.pkg.14.3.0
com.microsoft.office.all.word.pkg.14.3.9.update
com.microsoft.office.en.automator_workflow.pkg.14.3.0
com.microsoft.office.en.automator_workflow.pkg.14.3.9.update
com.microsoft.office.en.clipart.pkg.14.3.0
com.microsoft.office.en.clipart.pkg.14.3.9.update
com.microsoft.office.en.core_resources.pkg.14.3.0
com.microsoft.office.en.core_resources.pkg.14.3.9.update
com.microsoft.office.en.core_themes.pkg.14.3.0
com.microsoft.office.en.dcc_resources.pkg.14.3.0
com.microsoft.office.en.dcc_resources.pkg.14.3.9.update
com.microsoft.office.en.equationeditor_resources.pkg.14.3.0
com.microsoft.office.en.equationeditor_resources.pkg.14.3.9.update
com.microsoft.office.en.excel_resources.pkg.14.3.0
com.microsoft.office.en.excel_resources.pkg.14.3.9.update
com.microsoft.office.en.excel_templates.pkg.14.3.0
com.microsoft.office.en.excel_templates.pkg.14.3.9.update
com.microsoft.office.en.excel_webqueries.pkg.14.3.0
com.microsoft.office.en.flip4mac.pkg.14.3.0
com.microsoft.office.en.fonts_fontcollection.pkg.14.3.0
com.microsoft.office.en.graph_resources.pkg.14.3.0
com.microsoft.office.en.graph_resources.pkg.14.3.9.update
com.microsoft.office.en.langregister.pkg.14.3.0
com.microsoft.office.en.langregister.pkg.14.3.9.update
com.microsoft.office.en.outlook_resources.pkg.14.3.0
com.microsoft.office.en.outlook_resources.pkg.14.3.9.update
com.microsoft.office.en.outlook_scriptmenuitems.pkg.14.3.0
com.microsoft.office.en.outlook_scriptmenuitems.pkg.14.3.9.update
com.microsoft.office.en.powerpoint_guidedmethods.pkg.14.3.0
com.microsoft.office.en.powerpoint_resources.pkg.14.3.0
com.microsoft.office.en.powerpoint_resources.pkg.14.3.9.update
com.microsoft.office.en.powerpoint_templates.pkg.14.3.0
com.microsoft.office.en.query.pkg.14.3.0
com.microsoft.office.en.query.pkg.14.3.9.update
com.microsoft.office.en.readme.pkg.14.3.0
com.microsoft.office.en.readme.pkg.14.3.9.update
com.microsoft.office.en.required.pkg.14.3.0
com.microsoft.office.en.setupasst_resources.pkg.14.3.0
com.microsoft.office.en.sharepointbrowserplugin_resources.pkg.14.3.0
com.microsoft.office.en.sharepointbrowserplugin_resources.pkg.14.3.9.update
com.microsoft.office.en.silverlight.pkg.14.3.0
com.microsoft.office.en.solver.pkg.14.3.0
com.microsoft.office.en.solver.pkg.14.3.9.update
com.microsoft.office.en.sounds.pkg.14.3.0
com.microsoft.office.en.vb_resources.pkg.14.3.0
com.microsoft.office.en.word_resources.pkg.14.3.0
com.microsoft.office.en.word_resources.pkg.14.3.9.update
com.microsoft.office.en.word_templates.pkg.14.3.0
com.microsoft.office.en.word_wizards.pkg.14.3.0
com.microsoft.office.en.word_wizards.pkg.14.3.9.update
)

for receipt in "${pkg_remove[@]}"; do
    /usr/sbin/pkgutil --forget "${receipt}"
done
