#!/bin/bash

which lynx &> /dev/null || { printf "\n%s\n" "Lynx is not on this machine"; exit 1; }

read -r -p "What is the url? " url 

read -r -p "What should we call this download? " dir 

mkdir -p "$HOME/Desktop/${dir}"

cd "$HOME/Desktop/${dir}"

for pic in $(lynx --dump "${url}" | awk '/[Jj][Pp]*[Gg]$/{print $2}' | uniq); do
    wget "${pic}"
done
